prodotto.selectByFilter = select s from Prodotto s \
left join s.categoria cat \
left join s.produttore prod \
where (:categoria is null or cat.id = :categoria) \
and (:produttore is null or prod.id = :produttore)