spring.application.name=EcomBike

logging.level.root=info
logging.level.com.betacom=debug

logging.file.name=./EcomBike.log
logging.pattern.console=  %d{"yyyy/MM/dd HH:mm:ss,SSS"} [%p] [%t] %M\\(%F:%L\\) - %msg%n


server.port = 9080

spring.datasource.url=jdbc:postgresql://localhost:5432/ecombike
spring.datasource.username=postgres
#spring.datasource.password=admin
spring.datasource.password=${MY_DB_PASSWORD}


spring.jpa.show-sql= false

spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.jakarta.persistence.schema-generation.scripts.action=drop-and-create
spring.jpa.properties.jakarta.persistence.schema-generation.scripts.create-target=sql/define.sql
spring.jpa.properties.jakarta.persistence.schema-generation.scripts.drop-target=sql/drop.sql
spring.jpa.properties.hibernate.hbm2ddl.schema-generation.script.append=false

lang=IT

app.upload.dir=uploads
