
    create table anagrafica (
        id bigint generated by default as identity,
        cap varchar(10) not null,
        codice_fiscale varchar(20),
        partita_iva varchar(20),
        telefono varchar(20) not null,
        nazione varchar(30) not null,
        citta varchar(50) not null,
        cognome varchar(50) not null,
        nome varchar(50) not null,
        via varchar(100) not null,
        utente_user_name varchar(255) unique,
        primary key (id)
    );

    create table categoria (
        id bigint generated by default as identity,
        descrizione varchar(255),
        primary key (id)
    );

    create table dettaglio_ordine (
        prodotto_id integer,
        quantita integer not null,
        id bigint generated by default as identity,
        ordine_id bigint,
        primary key (id)
    );

    create table indirizzo_spedizione (
        id bigint generated by default as identity,
        ordine_indirizzo bigint unique,
        cap varchar(10) not null,
        codice_fiscale varchar(20),
        partita_iva varchar(20),
        telefono varchar(20) not null,
        nazione varchar(30) not null,
        citta varchar(50) not null,
        cognome varchar(50) not null,
        nome varchar(50) not null,
        via varchar(100) not null,
        primary key (id)
    );

    create table messaggi_sistema (
        lang varchar(4) not null,
        code varchar(20) not null,
        messaggio varchar(255),
        primary key (lang, code)
    );

    create table ordine (
        data_ordine date,
        orario_ordine time(0),
        id bigint generated by default as identity,
        utente_id varchar(255),
        primary key (id)
    );

    create table pagamento (
        amount numeric(38,2),
        data_pagamento date,
        orario_pagamento time(0),
        id bigint generated by default as identity,
        ordine_pagamento bigint unique,
        tipo_pagamento bigint,
        primary key (id)
    );

    create table prodotto (
        peso numeric(38,2),
        product_code integer not null,
        quantita integer not null,
        categoria_id bigint,
        produttore_id bigint,
        taglia varchar(20),
        colore varchar(200),
        descrizione varchar(200) not null,
        primary key (product_code)
    );

    create table produttore (
        id bigint generated by default as identity,
        codice_fiscale varchar(20),
        partita_iva varchar(20),
        marchio varchar(255),
        nome_azienda varchar(255),
        primary key (id)
    );

    create table tipo_pagamento (
        id bigint generated by default as identity,
        societa_creditrice varchar(255) not null,
        tipo_pagamento varchar(255) not null,
        primary key (id)
    );

    create table utente (
        role smallint check ((role between 0 and 3)),
        email varchar(255),
        password varchar(255),
        user_name varchar(255) not null,
        primary key (user_name)
    );

    alter table if exists anagrafica 
       add constraint FKbsc97wtuy3wnf5q9p2n7a44en 
       foreign key (utente_user_name) 
       references utente;

    alter table if exists dettaglio_ordine 
       add constraint FKg8p950u9hg0towv49etgqvfo2 
       foreign key (ordine_id) 
       references ordine;

    alter table if exists dettaglio_ordine 
       add constraint FKofsv22kynl273k3meewu00yrr 
       foreign key (prodotto_id) 
       references prodotto;

    alter table if exists indirizzo_spedizione 
       add constraint FKdgh66lk2x1vbnp6ca8kbjcvlq 
       foreign key (ordine_indirizzo) 
       references ordine;

    alter table if exists ordine 
       add constraint FKdg320enjlk6khf1wx5x8o28qx 
       foreign key (utente_id) 
       references utente;

    alter table if exists pagamento 
       add constraint FKnnhmthau4vxeibihypqc1c4sx 
       foreign key (ordine_pagamento) 
       references ordine;

    alter table if exists pagamento 
       add constraint FKlokfc657jetko2tqpe3y812ip 
       foreign key (tipo_pagamento) 
       references tipo_pagamento;

    alter table if exists prodotto 
       add constraint FKp54y50a2i7pdiipduc60tttrw 
       foreign key (categoria_id) 
       references categoria;

    alter table if exists prodotto 
       add constraint FKakof6q73twbk4tk150ann5gg9 
       foreign key (produttore_id) 
       references produttore;
