
    create table indirizzi (
        id bigint generated by default as identity,
        cap varchar(10) not null,
        citta varchar(50) not null,
        via varchar(100) not null,
        primary key (id)
    );

    create table utente (
        role smallint check ((role between 0 and 3)),
        email varchar(255),
        password varchar(255),
        user_name varchar(255) not null,
        primary key (user_name)
    );
